---
title: Створення нового проекту Scratch
hero_image: images / banner.png
description: Створіть новий проект Scratch
original_url:
theme: cc-прототип
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "подряпати"
steps:
  - 
    title: Створити новий проект
