---
title: Een nieuw Scratch-project maken
hero_image: images / banner.png
description: Maak een nieuw Scratch-project
original_url: ""
theme: cc-prototype
duration: 1
curriculum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - 
    title: Maak een nieuw project
