---
title: Создание нового проекта Scratch
hero_image: images/banner.png
description: Создаeм новый проект Scratch
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: Создаeм новый проект
