title: नया Scratch प्रोजेक्ट बनाना
hero_image: images/banner.png
description: नया Scratch प्रोजेक्ट बनाएं
original_url:
theme: cc-prototype
duration: 1 # 1, 2 or 3
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: “scratch"
steps:
  - title: नया प्रोजेक्ट बनाएं
