---
title: Креирање новог Сцратцх пројекта
hero_image: имагес / баннер.пнг
description: Креирајте нови Сцратцх пројекат
original_url:
theme: цц-прототип
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "огреботина"
steps:
  - 
    title: Креирајте нови пројекат
