---
title: Opprette et nytt Scratch-prosjekt
hero_image: images / banner.png
description: Lag et nytt Scratch-prosjekt
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "ripe"
steps:
  - 
    title: Lag et nytt prosjekt
