---
title: Erstellen eines neuen Scratch-Projekts
hero_image: Bilder / Banner.png
description: Erstellen Sie ein neues Scratch-Projekt
original_url: ""
theme: cc-Prototyp
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "kratzen"
steps:
  - 
    title: Erstellen Sie ein neues Projekt
