---
title: Creare un nuovo progetto Scratch
hero_image: images / banner.png
description: Crea un nuovo progetto Scratch
original_url: ""
theme: cc-prototipo
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "graffiare"
steps:
  - 
    title: Crea un nuovo progetto
