---
title: Oprettelse af et nyt Scratch-projekt
hero_image: images / banner.png
description: Opret et nyt Scratch-projekt
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "kradse"
steps:
  - 
    title: Opret et nyt projekt
