---
title: 创建一个新的 Scratch 项目
hero_image: images/banner.png
description: 创建一个新的 Scratch 项目
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: 创建一个新项目
