---
title: Stvaranje novog Scratch projekta
hero_image: images/banner.png
description: Napravi novi Scratch projekt
original_url: ""
theme: cc-prototype
duration: 1
curriculum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - 
    title: Napravi novi projekt
