---
title: Uuden Scratch-projektin luominen
hero_image: Kuvien / banner.png
description: Luo uusi Scratch-projekti
original_url:
theme: CC-prototyyppi
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "naarmu"
steps:
  - 
    title: Luo uusi projekti
