---
title: Uuden Scratch-projektin luominen
hero_image: images/banner.png
description: Luo uusi Scratch-projekti
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: Luo uusi projekti
