---
title: Crear un nuevo proyecto en Scratch
hero_image: images/banner.png
description: Crea un nuevo proyecto en Scratch
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - title: Crea un nuevo proyecto
