---
title: Creando un nuevo proyecto Scratch
hero_image: images / banner.png
description: Crea un nuevo proyecto Scratch
original_url: ""
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "rasguño"
steps:
  - 
    title: Crea un nuevo proyecto
