---
title: Ein neues Scratch-Projekt erstellen
hero_image: images/banner.png
description: Erstelle ein neues Scratch-Projekt
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: Erstelle ein neues Projekt
