---
title: Erstellen eines neuen Scratch-Projekts
hero_image: images/banner.png
description: Ein neues Scratch-Projekt erstellen
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: Erstelle ein neues Projekt
