---
title: Crearea unui nou proiect Scratch
hero_image: images / banner.png
description: Creați un nou proiect Scratch
original_url: ""
theme: cc-prototip
duration: 1
curriculum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "zgârietură"
steps:
  - 
    title: Creați un nou proiect
