---
title: Criando um novo projeto Scratch
hero_image: images / banner.png
description: Crie um novo projeto Scratch
original_url: ""
theme: protótipo cc
duration: 1
curriculum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "coçar, arranhão"
steps:
  - 
    title: Criar um novo projeto
