---
title: Criando um novo projeto Scratch
hero_image: images/banner.png
description: Crie um novo projeto Scratch
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: Crie um novo projeto
