---
title: Membuat proyek Scratch baru
hero_image: gambar / banner.png
description: Buat proyek Scratch baru
original_url: ""
theme: cc-prototipe
duration: 1
curriculum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "menggaruk"
steps:
  - 
    title: Buat proyek baru
