---
title: Membuat sebuah proyek Scratch baru
hero_image: images/banner.png
description: Buat sebuah proyek Scratch baru
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: Membuat sebuah proyek baru
