---
title: Ustvarjanje novega projekta Scratch
hero_image: images / banner.png
description: Ustvarite nov projekt Scratch
original_url: ""
theme: cc-prototip
duration: 1
curriculum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "praska"
steps:
  - 
    title: Ustvarite nov projekt
