---
title: Új Scratch projekt létrehozása
hero_image: images / banner.png
description: Hozzon létre egy új Scratch projektet
original_url:
theme: cc-prototípus
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "karcolás"
steps:
  - 
    title: Hozzon létre egy új projektet
