---
title: Créer un nouveau projet Scratch
hero_image: images / banner.png
description: Créer un nouveau projet Scratch
original_url: ""
theme: cc-prototype
duration: 1
curriculum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "rayure"
steps:
  - 
    title: Créer un nouveau projet
