---
title: Vytvorenie nového projektu Scratch
hero_image: images / banner.png
description: Vytvorte nový projekt Scratch
original_url: ""
theme: cc-prototyp
duration: 1
curriculum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "škrabanec"
steps:
  - 
    title: Vytvorte nový projekt
