---
title: Skapa ett nytt Scratch-projekt
hero_image: images / banner.png
description: Skapa ett nytt Scratch-projekt
original_url:
theme: cc-prototyp
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "repa"
steps:
  - 
    title: Skapa ett nytt projekt
