---
title: Membuat projek Scratch baru
hero_image: imej / banner.png
description: Buat projek Scratch baru
original_url:
theme: prototaip cc
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "awal"
steps:
  - 
    title: Buat projek baru
