---
title: Kreiranje novog Scratch projekta
hero_image: images/banner.png
description: Kreiraj novi Scratch projekat
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - title: Kreiraj novi projekat
