---
title: Créer un nouveau projet Scratch
hero_image: images/banner.png
description: Crée un nouveau projet Scratch
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - title: Crée un nouveau projet
