---
title: Creare un nuovo progetto di Scratch
hero_image: images/banner.png
description: Creare un nuovo progetto di Scratch
original_url: ""
theme: cc-prototype
duration: 1
curriculum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - title: Crea un nuovo progetto
