---
title: Yeni bir Scratch projesi oluşturmak
hero_image: images / banner.png
description: Yeni bir Scratch projesi oluştur
original_url:
theme: cc-prototip
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "çizik"
steps:
  - 
    title: Yeni bir proje oluştur
