---
title: Yeni bir Scratch projesi oluşturma
hero_image: images/banner.png
description: Yeni bir Scratch projesi oluşturun
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: Yeni bir proje oluşturun
